menu:
  - build
  - kadena
  - blogchain
  - chainweb

pages:
  build:
    title: Build
    url: /test
    file: /docs/test.md
    children:
      build:
        title: Build
        url: /build
        file: /docs/index.tsx
