menu:
  - quickstart
  - developers
  - pow
  - api
  - solutions

pages:
  quickstart:
    url: /quickstart
    file: /quick-start.md
  developers:
    url: /developers
    file: /developers.md
    children:
      learn-pact:
        url: /intro
        file: /developers/learn-pact/get-started-intro.md
      install:
        url: /install
        file: /developers/learn-pact/get-started-with-pact.md
      basics:
        url: /basic-concepts
        file: /developers/learn-pact/basic-concepts.md
      devnet:
        url: /dev-network
        file: /developers/learn-pact/dev-network.md
      languagebasics:
        url: /language-basics
        file: /developers/learn-pact/language-basics.md
      modules:
        url: /modules
        file: /developers/learn-pact/modules.md
      keysets:
        url: /keysets
        file: /developers/learn-pact/keysets.md
      schemastables:
        url: /schemas-and-tables
        file: /developers/learn-pact/schemas-and-tables.md
      pacts:
        url: /pacts
        file: /developers/pact-reference/pacts.md

  projects:
    url: /coding-projects
    file: /coding-projects.md
    children:
      accountstransfers:
        url: /accounts-and-transfers
        file: /developers/learn-pact/accounts-and-transfers.md
      contractinteraction:
        url: /contract-interaction
        file: /developers/learn-pact/contract-interaction.md
      rotatablewallet:
        url: /rotatable-wallet
        file: /developers/learn-pact/rotatable-wallet.md
      loans:
        url: /loans
        file: /developers/learn-pact/loans.md
      testsdk:
        url: /test-in-the-sdk
        file: /developers/learn-pact/test-in-the-sdk.md
      localserver:
        url: /local-server
        file: /developers/learn-pact/deploy-local-server.md
      pactjavascript:
        url: /pact-and-javascript
        file: /developers/learn-pact/pact-and-javascript.md
  reference:
    url: /reference
    file: /reference.md
    children:
      pactsyntax:
        url: /syntax
        file: /developers/pact-reference/syntax.md
      functions:
        url: /functions
        file: /developers/pact-reference/pact-ref.md
        children:
          general:
            url: /general
            file: /developers/pact-reference/functions/general-functions.md
            repo: https://github.com/kadena-io/pact-5
            dir: /docs/builtins/General
          database:
            url: /database
            file: /developers/pact-reference/functions/database-functions.md
            repo: https://github.com/kadena-io/pact-5
            dir: /docs/builtins/Database
          replonlyfunctions:
            url: /repl-only-functions
            file: /developers/pact-reference/functions/repl-only-functions.md
            repo: https://github.com/kadena-io/pact-5
            dir: /docs/builtins/Repl
        kadena-cli:
          url: /kadena-cli
          file: /developers/cli-ref.md
          children:
            account:
              url: /account
              file: /developers/cli/cli-account.md
            config:
              url: /config
              file: /developers/cli/cli-config.md
            dapp:
              url: /dapp
              file: /developers/cli/cli-dapp.md
            key:
              url: /key
              file: /developers/cli/cli-key.md
            network:
              url: /network
              file: /developers/cli/cli-network.md
            tx:
              url: /tx
              file: /developers/cli/cli-tx.md
            wallet:
              url: /wallet
              file: /developers/cli/cli-wallet.md
        frontend:
          url: /kadena-client
          file: /developers/kadena-client/kadena-js.md
          children:
            client-utils:
              url: /client-utils
              file: /developers/kadena-client/client-utils.md
            pactjscli:
              url: /pactjs-cli
              file: /developers/kadena-client/pactjs-cli.md
            pactjsgenerator:
              url: /pactjs-generator
              file: /developers/kadena-client/pactjs-generator.md
            cryptographyutils:
              url: /cryptographic-utils
              file: /developers/kadena-client/cryptographic-utils.md
  pow:
    url: /consensus
    file: /pow/consensus.md
    children:
      chainweb:
        url: /chainweb
        file: /pow/chainweb-simplified.md
      getstarted:
        url: /get-started
        file: /pow/chainweb-get-started.md
      compactdb:
        url: /compact-databases
        file: /pow/compact-a-database.md
      config:
        url: /config-options
        file: /pow/configure-node-options.md
  how-to:
    url: /how-to
    file: /how-to/code-templates.md
  api:
    url: /api
    file: /kadena-api/chainweb-api.md
    children:
      blockhash:
        url: /blockhash
        file: /kadena-api/chainweb-blockhash.md
      blockheader:
        url: /blockheader
        file: /kadena-api/chainweb-blockheader.md
      chainwebconfig:
        url: /config
        file: /kadena-api/chainweb-config.md
      cut:
        url: /cut
        file: /kadena-api/chainweb-cut.md
      mempool:
        url: /mempool
        file: /kadena-api/chainweb-mempool.md
      payload:
        url: /payload
        file: /kadena-api/chainweb-payload.md
  solutions:
    url: /solutions
    file: /solutions.md
    children:
      onboard:
        url: /onboard
        file: /solutions/explore-on-chain.md
      nft-marmalade:
        url: /nft-marmalade
        file: /solutions/nft-marmalade/what-is-marmalade.md
        children:
          qetstarted:
            url: /get-started
            file: /solutions/nft-marmalade/get-started.md
          architecture:
            url: /architecture
            file: /solutions/nft-marmalade/contract-architecture.md
          metadata:
            url: /metadata
            file: /solutions/nft-marmalade/metadata.md
          storage:
            url: /storage
            file: /solutions/nft-marmalade/storage.md
          nft:
            url: /create-nft
            file: /solutions/nft-marmalade/create-nft.md
          collection:
            url: /create-a-collection
            file: /solutions/nft-marmalade/create-a-collection.md
          concretepolicies:
            url: /concrete-policies
            file: /solutions/nft-marmalade/concrete-policies.md
            children:
              examplepolicies:
                url: /example-policies
                file: /solutions/nft-marmalade/example-policies.md
              custompolicies:
                url: /custom-policies
                file: /solutions/nft-marmalade/custom-policies.md
          sales:
            url: /sales
            file: /solutions/nft-marmalade/sale-contracts.md
            children:
              auctions:
                url: /auctions
                file: /solutions/nft-marmalade/auctions.md
              startsale:
                url: /start-a-sale
                file: /solutions/nft-marmalade/start-a-sale.md
              createauction:
                url: /create-an-auction
                file: /solutions/nft-marmalade/create-an-auction.md
      authentication:
        url: /authentication
        file: /solutions/authentication/authenticate-overview.md
        children:
          register:
            url: /register
            file: /solutions/authentication/register-an-account.md
          integrate:
            url: /integrate
            file: /solutions/authentication/integrate-an-app.md
          createtx:
            url: /transactions
            file: /solutions/authentication/create-transactions.md
          recover:
            url: /recover
            file: /solutions/authentication/recover-account.md
      election:
        url: /election
        file: /solutions/election-app/index.md
        children:
          prepare:
            url: /prepare-your-workspace
            file: /solutions/election-app/prepare-your-workspace.md
          start:
            url: /start-a-local-blockchain
            file: /solutions/election-app/start-a-local-blockchain.md
          admin:
            url: /add-admin-account
            file: /solutions/election-app/add-admin-account.md
          namespace:
            url: /define-a-namespace
            file: /solutions/election-app/define-a-namespace.md
          keysets:
            url: /define-keysets
            file: /solutions/election-app/define-keysets.md
          smartcontract:
            url: /write-a-smart-contract
            file: /solutions/election-app/write-a-smart-contract.md
          candidates:
            url: /nominate-candidates
            file: /solutions/election-app/nominate-candidates.md
          voting:
            url: /add-vote-management
            file: /solutions/election-app/add-vote-management.md
          gasstation:
            url: /add-a-gas-station
            file: /solutions/election-app/add-a-gas-station.md
      faucet:
        url: /faucet
        file: /solutions/faucet-app.md
