menu:
  - learn
  - build
  - deploy
  - participate
  - invest
  - tutorials
  - reference

pages:
  learn:
    url: /learn
    file: /learn/learn.md
    children:
      blockchain:
        url: /what-is-a-blockchain
        file: /learn/what-is-a-blockchain.md
      whybuild:
        url: /why-build
        file: /learn/why-build.md
      cryptography:
        url: /cryptography
        file: /learn/cryptography.md
      whykadena:
        url: /why-kadena
        file: /learn/why-kadena.md
      consensus:
        url: /consensus
        file: /learn/consensus.md
      chainweb:
        url: /chainweb
        file: /learn/chainweb-simplified.md
      accounts:
        url: /accounts
        file: /learn/accounts-keys.md
      glossary:
        url: /glossary
        file: /learn/glossary.md
      kadena-faq:
        url: /kadena-faq
        file: /learn/kadena-faq.md
      resources:
        url: /resources
        file: /learn/resources.md

  build:
    url: /build
    file: /build/build.md
    children:
      onboard:
        url: /onboard
        file: /explore-on-chain.md
      quickstart:
        url: /quickstart
        file: /quick-start.md
      pact:
        url: /pact
        file: /build/pact/get-started-with-pact.md
        children:
          devnet:
            url: /dev-network
            file: /build/pact/beginner/dev-network.md
          helloworld:
            url: /hello-world
            file: /build/pact/beginner/hello-world.md
          languagebasics:
            url: /language-basics
            file: /build/pact/beginner/language-basics.md
          modules:
            url: /modules
            file: /build/pact/beginner/modules.md
          keysets:
            url: /keysets
            file: /build/pact/beginner/keysets.md
          schemastables:
            url: /schemas-and-tables
            file: /build/pact/beginner/schemas-and-tables.md
          atomsdk:
            url: /atom-sdk
            file: /build/pact/beginner/atom-sdk.md
          accountstransfers:
            url: /accounts-and-transfers
            file: /build/pact/beginner/accounts-and-transfers.md
          contractinteraction:
            url: /contract-interaction
            file: /build/pact/beginner/contract-interaction.md
          rotatablewallet:
            url: /rotatable-wallet
            file: /build/pact/beginner/rotatable-wallet.md
          loans:
            url: /loans
            file: /build/pact/beginner/loans.md
          testsdk:
            url: /test-in-the-sdk
            file: /build/pact/beginner/test-in-the-sdk.md
          localserver:
            url: /local-server
            file: /build/pact/intermediate/deploy-local-server.md
          pactjavascript:
            url: /pact-and-javascript
            file: /build/pact/intermediate/pact-and-javascript.md
          safetyflow:
            url: /safety-using-control-flow
            file: /build/pact/intermediate/safety-using-control-flow.md
          interfacespact:
            url: /interfaces-with-pact
            file: /build/pact/intermediate/interfaces-with-pact.md
          builtinfunctions:
            url: /built-in-functions
            file: /build/pact/intermediate/built-in-functions.md
      nftmarmalade:
        url: /nft-marmalade
        file: /build/nft-marmalade/what-is-marmalade.md
        children:
          qetstarted:
            url: /get-started
            file: /build/nft-marmalade/get-started.md
          architecture:
            url: /architecture
            file: /build/nft-marmalade/contract-architecture.md
          metadata:
            url: /metadata
            file: /build/nft-marmalade/metadata.md
          storage:
            url: /storage
            file: /build/nft-marmalade/storage.md
          nft:
            url: /create-nft
            file: /build/nft-marmalade/create-nft.md
          collection:
            url: /create-a-collection
            file: /build/nft-marmalade/create-a-collection.md
          concretepolicies:
            url: /concrete-policies
            file: /build/nft-marmalade/concrete-policies.md
      frontend:
        url: /frontend
        file: /build/frontend.md
      templates:
        url: /templates
        file: /build/code-templates.md
      election:
        url: /election
        file: /build/election-app/index.md
        children:
          prepare:
            url: /prepare-your-workspace
            file: /build/election-app/prepare-your-workspace.md
          start:
            url: /start-local-blockchain
            file: /build/election-app/start-a-local-blockchain.md
          admin:
            url: /add-admin-account
            file: /build/election-app/add-admin-account.md
          namespace:
            url: /define-a-namespace
            file: /build/election-app/define-a-namespace.md
          keysets:
            url: /define-keysets
            file: /build/election-app/define-keysets.md
          smartcontract:
            url: /write-a-smart-contract
            file: /build/election-app/write-a-smart-contract.md
          candidates:
            url: /nominate-candidates
            file: /build/election-app/nominate-candidates.md
          voting:
            url: /add-vote-management
            file: /build/election-app/add-vote-management.md
          gasstation:
            url: /add-a-gas-station
            file: /build/election-app/add-a-gas-station.md
      faucet:
        url: /faucet
        file: /faucet-app.md
      nft-marketplace:
        url: /nft-marketplace
        file: /build/nft-marketplace.md
  deploy:
    url: /deploy
    file: /deploy/deploy.md
    children:
      getstarted:
        url: /chainweb-get-started
        file: /deploy/chainweb/chainweb-get-started.md
      compactdb:
        url: /compact-database
        file: /deploy/chainweb/compact-a-database.md
  invest:
    url: /invest
    file: /invest/invest.md
    children:
      exchanges:
        url: /exchanges
        file: /invest/exchanges.md
      wallets:
        url: /wallets
        file: /invest/wallets.md
  participate:
    url: /participate
    file: /participate/participate.md
    children:
      community:
        url: /community
        file: /participate/community.md
      nodeoperators:
        url: /node
        file: /participate/node/index.md
      docs:
        url: /docs
        file: /participate/docs.md
      developers:
        url: /developers
        file: /participate/developer.md
  tutorials:
    url: /tutorials
    file: /tutorials/tutorials.md
    children:
      pactbeginner:
        url: /beginner
        file: /tutorials/beginner/index.md
        children:
          webeditor:
            url: /web-editor
            file: /tutorials/beginner/dev-network.md
          helloworld:
            url: /hello-world
            file: /tutorials/beginner/hello-world.md
          languagebasics:
            url: /language-basics
            file: /tutorials/beginner/language-basics.md
          modules:
            url: /modules
            file: /tutorials/beginner/modules.md
          keysets:
            url: /keysets
            file: /tutorials/beginner/keysets.md
          schemastables:
            url: /schemas-and-tables
            file: /tutorials/beginner/schemas-and-tables.md
          atomsdk:
            url: /atom-sdk
            file: /tutorials/beginner/atom-sdk.md
          accountstransfers:
            url: /accounts-and-transfers
            file: /tutorials/beginner/accounts-and-transfers.md
          contractinteraction:
            url: /contract-interaction
            file: /tutorials/beginner/contract-interaction.md
          rotatablewallet:
            url: /rotatable-wallet
            file: /tutorials/beginner/rotatable-wallet.md
          loans:
            url: /loans
            file: /tutorials/beginner/loans.md
          testsdk:
            url: /test-in-the-sdk
            file: /tutorials/beginner/test-in-the-sdk.md
        pactintermediate:
          url: /intermediate
          file: /tutorials/intermediate/index.md
          children:
            pactjavascript:
              url: /pact-and-javascript
              file: /tutorials/intermediate/pact-and-javascript.md
            safetyflow:
              url: /safety-using-control-flow
              file: /tutorials/intermediate/safety-using-control-flow.md
            interfacespact:
              url: /interfaces-with-pact
              file: /tutorials/intermediate/interfaces-with-pact.md
            builtinfunctions:
              url: /built-in-functions
              file: /tutorials/intermediate/built-in-functions.md
  reference:
    url: /reference
    file: /reference/reference.md
    children:
      pactsyntax:
        url: /syntax
        file: /reference/pact/syntax.md
      functions:
        url: /functions
        file: /reference/pact/pact-ref.md
        children:
          general:
            url: /general
            file: /reference/pact/functions/general-functions.md            
          database:
            url: /database
            file: /reference/pact/functions/database-functions.md
          time:
            url: /time
            file: /reference/pact/functions/time.md
          operators:
            url: /operators
            file: /reference/pact/functions/operators.md
          keysets:
            url: /keysets
            file: /reference/pact/functions/keysets.md
          capabilities:
            url: /capabilities
            file: /reference/pact/functions/capabilities.md
          spv:
            url: /spv
            file: /reference/pact/functions/spv.md
          commitments:
            url: /commitments
            file: /reference/pact/functions/commitments.md
          guards:
            url: /guards
            file: /reference/pact/functions/guards.md
          zk:
            url: /zk
            file: /reference/pact/functions/zk.md
          replonlyfunctions:
            url: /repl-only-functions
            file: /reference/pact/functions/repl-only-functions.md
      propertychecking:
        url: /property-checking
        file: /reference/pact/property-checking.md
        children:
          numerical:
            url: /numerical
            file: /reference/pact/properties-and-invariants/numerical.md
          bitwise:
            url: /bitwise
            file: /reference/pact/properties-and-invariants/bitwise.md
          objectoperators:
            url: /object-operators
            file: /reference/pact/properties-and-invariants/object-operators.md
          listoperators:
            url: /list-operators
            file: /reference/pact/properties-and-invariants/list-operators.md
          string:
            url: /string
            file: /reference/pact/properties-and-invariants/string.md
          temporal:
            url: /temporal
            file: /reference/pact/properties-and-invariants/temporal.md
          quantification:
            url: /quantification
            file: /reference/pact/properties-and-invariants/quantification.md
          transactional:
            url: /transactional
            file: /reference/pact/properties-and-invariants/transactional.md
          database:
            url: /database
            file: /reference/pact/properties-and-invariants/database.md
          authorization:
            url: /authorization
            file: /reference/pact/properties-and-invariants/authorization.md
          function:
            url: /function
            file: /reference/pact/properties-and-invariants/function.md
          other:
            url: /other
            file: /reference/pact/properties-and-invariants/other.md
      pacts:
        url: /pacts
        file: /reference/pact/pacts.md  
      pactrepl:
        url: /pact-repl
        file: /reference/pact/pact-repl-cli.md
      pactjs:
        url: /pactjs
        file: /reference/pact/pactjs-api.md
      restapi:
        url: /rest-api
        file: /reference/pact/rest-api.md
      frontend:
        url: /kadena-client
        file: /reference/kadena-client/client-utils.md
        children:
          kadena-cli:
            url: /kadena-cli
            file: /reference/kadena-client/kadena-cli.md
          kadena-js:
            url: /kadena-js
            file: /reference/kadena-client/kadena-js.md
      marmalade:
        url: /ledger
        file: /reference/marmalade/ledger.md
        children:
          policymanager:
            url: /policy-manager
            file: /reference/marmalade/policy-manager.md
          salecontract:
            url: /sale-contracts
            file: /reference/marmalade/sale-contracts.md
          auction:
            url: /auctions
            file: /reference/marmalade/auction-ref.md
          policies:
            url: /policies
            file: /reference/marmalade/policies.md
            children:
              guard:
                url: /guard-policy
                file: /reference/marmalade/guard-policy.md
              nftpolicy:
                url: /nft-policy
                file: /reference/marmalade/non-fungible-policy.md
              royalty:
                url: /royalty-policy
                file: /reference/marmalade/royalty-policy.md
              collection:
                url: /collection-policy
                file: /reference/marmalade/collection-policy.md
      chainweb:
        url: /chainweb
        file: /reference/chainweb/chainweb.md
        children:
          nodeclient:
            url: /node-client
            file: /reference/chainweb/chainweb-node.md
          streamclient:
            file: /reference/chainweb/chainweb-stream.md
            url: /stream-client
          jsbindings:
            file: /reference/chainweb/chainwebjs.md
            url: /js-bindings
