menu:
  - kadena
  - build
  - pact
  - chainweb
  - marmalade
  - contribute
  - blogchain

pages:
  build:
    title: Build
    url: /test
    file: /docs/test.md
    children:
      build:
        title: Build
        url: /build
        file: /docs/index.tsx
      build2:
        title: Build2
        url: /build2
        file: /docs/test.md
