
menu:
  - learn
  - build
  - deploy
  - participate
  - invest
  - tutorials
  - reference

pages:
  learn:
    url: /learn
    file: /learn/learn.md
    children:
      what-is-kadena:
        url: /what-is-kadena
        file: /learn/what-is-kadena.md
      concepts:
        url: /concepts
        file: /learn/concepts.md
      overview:
        url: /overview
        file: /learn/overview.md
      accounts:
        url: /accounts
        file: /learn/accounts-keys.md
  build:
    url: /build
    file: /build/build.md
    children:
      quickstart:
        url: /quickstart
        file: /quick-start.md
      pact:
        url: /pact
        file: /build/pact/build-with-pact.md
        children:
          helloworld:
            url: /hello-world
            file: /build/pact/beginner/hello-world.md
      electionapp:
        url: /election
        file: /build/election-app/index.md
        children:
          prepare:
            url: /prepare-your-workspace
            file: /build/election-app/01-getting-started.md
          start:
            url: /start-local-blockchain
            file: /build/election-app/start-a-local-blockchain.md
      faucet:
        url: /faucet
        file: /faucet-app.md
      marmalade:
        url: /marmalade
        file: /build/nft-marketplace.md
  deploy:
    url: /deploy
    file: /deploy/deploy.md
  invest:
    url: /invest
    file: /invest/invest.md
    children:
      kda:
        url: /kda
        file: /invest/what-is-kda.md
      exchanges:
        url: /exchanges
        file: /invest/exchanges.md
  participate:
    url: /participate
    file: /participate/participate.md
    children:
      ambassadors:
        url: /ambassadors
        file: /participate/ambassadors.md
      nodeoperators:
        url: /node
        file: /participate/node/index.md
      docs:
        url: /docs
        file: /participate/docs.md
      developers:
        url: /developers
        file: /participate/developer.md
  tutorials:
    url: /tutorials
    file: /tutorials/tutorials.md
    children:
      pactbeginner:
        url: /beginner
        file: /tutorials/beginner/index.md
        children:
          webeditor:
            url: /web-editor
            file: /tutorials/beginner/web-editor.md
          helloworld:
            url: /hello-world
            file: /tutorials/beginner/hello-world.md
          languagebasics:
            url: /language-basics
            file: /tutorials/beginner/language-basics.md
          modules:
            url: /modules
            file: /tutorials/beginner/modules.md
          keysets:
            url: /keysets
            file: /tutorials/beginner/keysets.md
          schemastables:
            url: /schemas-and-tables
            file: /tutorials/beginner/schemas-and-tables.md
          atomsdk:
            url: /atom-sdk
            file: /tutorials/beginner/atom-sdk.md
          accountstransfers:
            url: /accounts-and-transfers
            file: /tutorials/beginner/accounts-and-transfers.md
          contractinteraction:
            url: /contract-interaction
            file: /tutorials/beginner/contract-interaction.md
          rotatablewallet:
            url: /rotatable-wallet
            file: /tutorials/beginner/rotatable-wallet.md
          loans:
            url: /loans
            file: /tutorials/beginner/loans.md
          testsdk:
            url: /test-in-the-sdk
            file: /tutorials/beginner/test-in-the-sdk.md
        pactintermediate:
          url: /intermediate
          file: /tutorials/intermediate/index.md
          children:
            pactjavascript:
              url: /pact-and-javascript
              file: /tutorials/intermediate/pact-and-javascript.md
            safetyflow:
              url: /safety-using-control-flow
              file: /tutorials/intermediate/safety-using-control-flow.md
            interfacespact:
              url: /interfaces-with-pact
              file: /tutorials/intermediate/interfaces-with-pact.md
            builtinfunctions:
              url: /built-in-functions
              file: /tutorials/intermediate/built-in-functions.md
  reference:
    url: /reference
    file: /reference/reference.md
    children:
      pact:
        url: /pact-ref
        file: /reference/pact/pact-ref.md
        children:
          general:
            url: /general
            file: /reference/pact/general-functions.md
          database:
            url: /database
            file: /reference/pact/database-functions.md
          time:
            url: /time
            file: /reference/pact/functions/time.md
          operators:
            url: /operators
            file: /reference/pact/functions/operators.md
          keysets:
            url: /keysets
            file: /reference/pact/functions/keysets.md
          capabilities:
            url: /capabilities
            file: /reference/pact/functions/capabilities.md
          spv:
            url: /spv
            file: /reference/pact/functions/spv.md
          commitments:
            url: /commitments
            file: /reference/pact/functions/commitments.md
          guards:
            url: /guards
            file: /reference/pact/functions/guards.md
          zk:
            url: /zk
            file: /reference/pact/functions/zk.md
          replonlyfunctions:
            url: /repl-only-functions
            file: /reference/pact/functions/repl-only-functions.md
      propertychecking:
        url: /property-checking
        file: /reference/pact/property-checking.md
      propertiesinvariants:
        url: /properties-and-invariants
        file: /reference/pact/properties-and-invariants/index.md
        children:
          numerical:
            url: /numerical
            file: /reference/pact/properties-and-invariants/numerical.md
          bitwise:
            url: /bitwise
            file: /reference/pact/properties-and-invariants/bitwise.md
          objectoperators:
            url: /object-operators
            file: /reference/pact/properties-and-invariants/object-operators.md
          listoperators:
            url: /list-operators
            file: /reference/pact/properties-and-invariants/list-operators.md
          string:
            url: /string
            file: /reference/pact/properties-and-invariants/string.md
          temporal:
            url: /temporal
            file: /reference/pact/properties-and-invariants/temporal.md
          quantification:
            url: /quantification
            file: /reference/pact/properties-and-invariants/quantification.md
          transactional:
            url: /transactional
            file: /reference/pact/properties-and-invariants/transactional.md
          database:
            url: /database
            file: /reference/pact/properties-and-invariants/database.md
          authorization:
            url: /authorization
            file: /reference/pact/properties-and-invariants/authorization.md
          function:
            url: /function
            file: /reference/pact/properties-and-invariants/function.md
          other:
            url: /other
            file: /reference/pact/properties-and-invariants/other.md
      api:
        url: /api
        file: /reference/pact/api/index.tsx
      pactjs:
        url: /pactjs
        file: /reference/pactjs.md
  blogchain:
    url: /blogchain
    file: /blogchain/index.tsx
    children:
      blog2023:
        url: /2023
        file: /blogchain/2023/index.tsx
      blog2022:
        url: /2022
        file: /blogchain/2022/index.tsx
      blog2021:
        url: /2021
        file: /blogchain/2021/index.tsx
      blog2020:
        url: /2020
        file: /blogchain/2020/index.tsx
      blog2019:
        url: /2019
        file: /blogchain/2019/index.tsx
      blog2018:
        url: /2018
        file: /blogchain/2018/index.tsx
