name: CI (build, test, format)
# All pull requests, and
# Workflow dispatch allows you to run this workflow manually from the Actions tab
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AFFECTED_OR_ALL: |
    ${{ github.ref_name == 'main' && ' ' || '--filter=[origin/main]'  }}

jobs:
  build:
    name: ${{ matrix.os }} - Node.js v${{ matrix.NodeVersion }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        NodeVersion: [16, 18]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Fetch base branch
        if: github.ref_name != 'main'
        run: git fetch origin ${{ github.base_ref }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint packages
        run: pnpm lint ${{ env.AFFECTED_OR_ALL }}

      - name: Build packages
        run: pnpm build ${{ env.AFFECTED_OR_ALL }}

      - name: Test packages
        run: pnpm test ${{ env.AFFECTED_OR_ALL }}

      - name: Verify source code formatting
        if: github.ref_name != 'main'
        run: pnpm run format:ci ${{ env.AFFECTED_OR_ALL }}
