name: Deploy to Vercel Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_ID }}
on:
 pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
       with:
          fetch-depth: 2
          show-progress: false

     - name: Runner Setup  
       uses: ./.github/actions/runner-setup
    
     - name: Install Vercel CLI
       run: pnpm add --global vercel@34.2.5

     - name: Link reop to Vercel
       run: vercel link --repo --yes --token=${{ secrets.VERCEL_TOKEN }}

     - name: Pull Vercel Environment Information
       run: vercel pull --cwd packages/apps/docs --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

     - name: Build App for Vercel Deployment
       run: vercel build --cwd packages/apps/docs --token=${{ secrets.VERCEL_TOKEN }}

     - name: Deploy Project Artifacts to Vercel
       run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz