name: Deploy to Vercel Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_ID }}
on:
 pull_request:

jobs:
  deploy:

    environment:
      name: preview
      url: ${{ steps.deployment.outputs.url }}
    
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
       with:
          fetch-depth: 0
          show-progress: false

     - name: Runner Setup  
       uses: ./.github/actions/runner-setup
    
     - name: Detecting App Changes
       id: detectChanges
       run: | 
        echo "Detecting Changes"

        # Enable Error Handling
        set +e

        npx turbo-ignore @kadena/docs -f ${{ github.base_ref }}
        exit_code=$?

        # Disable Error Handling
        set -e

        echo "exit_code: $exit_code"
        if [ $exit_code -eq 0 ]; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

     - name: Install Vercel CLI
       if: steps.detectChanges.outputs.changed == 'true' 
       run: pnpm add --global vercel@34.2.5 

     - name: Pull Vercel Environment Information
       if: steps.detectChanges.outputs.changed == 'true' 
       run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

     - name: Build App for Vercel Deployment
       if: steps.detectChanges.outputs.changed == 'true' 
       run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

     - name: Deploy Project Artifacts to Vercel
       if: steps.detectChanges.outputs.changed == 'true' 
       run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz | tee deploy.log
      
     - name: Set preview url
       id: deployment
       run: echo "url=$(tail -1 deploy.log)">> $GITHUB_OUTPUT