name: Deploy to Vercel Preview
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      app:
        description: "App to Deploy"
        required: true
        type: string
    secrets:
      VERCEL_PROJECT_ID:
        description: "Vercel Project ID"
        required: true
      VERCEL_ORG_ID:
        description: "Vercel Organization ID"
        required: true
      VERCEL_TOKEN:
        description: "Vercel Token"
        required: true

env: 
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  

jobs:
  deploy:
    name: ${{ inputs.app }}
    if: ${{ github.repository_owner == 'kadena-community' }} // Prevents auto deploying forks.

    environment:
      name: ${{ inputs.app }} - Preview
      url: ${{ steps.deployment.outputs.url }}
    
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
       with:
          fetch-depth: 0
          show-progress: false

     - name: Runner Setup  
       uses: ./.github/actions/runner-setup
    
     - name: Detecting App Changes
       id: detectChanges
       run: | 
        echo "Detecting Changes"

        # Enable Error Handling
        set +e

        npx turbo-ignore @kadena/${{ inputs.app }} -f origin/main
        exit_code=$?

        # Disable Error Handling
        set -e

        echo "exit_code: $exit_code"
        if [ $exit_code -eq 0 ]; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

     - name: Install Vercel CLI
       if: steps.detectChanges.outputs.changed == 'true' 
       run: pnpm add --global vercel@34.2.5 

     - name: Pull environment variables
       if: steps.detectChanges.outputs.changed == 'true' 
       run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

     - name: Build App
       if: steps.detectChanges.outputs.changed == 'true' 
       run: vercel build --token=${{ secrets.VERCEL_TOKEN }} --debug

     - name: Deploy App
       if: steps.detectChanges.outputs.changed == 'true' 
       run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --archive=tgz --meta pr_data=${{ github.event.repository.name }}-${{ github.event.number }} | tee deploy.log
      
     - name: Set preview url
       if: steps.detectChanges.outputs.changed == 'true' 
       id: deployment
       run: echo "url=$(tail -1 deploy.log)">> $GITHUB_OUTPUT