name: Rush release (version --bump, publish)
on:
  push:
    branches: ['develop']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Node.js v${{ matrix.NodeVersion }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NodeVersion: [14, 16]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Git config user
        run: |
          git config --local user.name "Rushbot Kadena"
          git config --local user.email "rushbot-kadena@users.noreply.github.com"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}
      - name: Rush verify Change Logs (install-run-rush)
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush install (install-run-rush)
        run: node common/scripts/install-run-rush.js install
      - name: Rush retest (install-run-rush)
        run: node common/scripts/install-run-rush.js retest --verbose
        env:
          # Prevent time-based browserslist update warning
          # See https://github.com/microsoft/rushstack/issues/2981
          BROWSERSLIST_IGNORE_OLD_DATA: 1
      - name: Rush version bump (install-run-rush)
        run: node common/scripts/install-run-rush.js version --bump --target-branch master --ignore-git-hooks
      - name: Rush publish (install-run-rush)
        run: node common/scripts/install-run-rush.js publish --apply --publish --include-all --add-commit-details --set-access-level public --target-branch master
      # - name: Rush test (rush-lib)
      #   run: node apps/rush/lib/start-dev.js test --verbose --production --timeline
      #   env:
      #     # Prevent time-based browserslist update warning
      #     # See https://github.com/microsoft/rushstack/issues/2981
      #     BROWSERSLIST_IGNORE_OLD_DATA: 1
      # - name: Ensure repo README is up-to-date
      #   run: node repo-scripts/repo-toolbox/lib/start.js readme --verify
