on: 
    pull_request:
jobs:
  docs-preview:
    name: Docs - Preview Deploymnt
    uses: ./.github/workflows/deploy-preview.yml
    with:
      app: 'docs'
    secrets:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_ID }}
      