name: Creating Preview environments
on: 
    pull_request:
jobs:
  docs-preview:
    name: Preview Deploymnt
    uses: ./.github/workflows/deploy-preview.yml
    with:
      app: 'docs'
    secrets:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  tools-preview:
    name: Preview Deploymnt
    uses: ./.github/workflows/deploy-preview.yml
    with:
      app: 'docs'
    secrets:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_TOOLS_ID }}
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}